### ISSUE TITLE
Notice: Undefined property

### ISSUE THREAD

**Issue by 810** [androidealp/kunema-countsimilar#1]
Notice: Undefined property: ComponentKunenaControllerTopicItemActionsDisplay::$me in plugins/kunena/countsimilar/countsimilar.php on line 45

Notice: Trying to get property of non-object in plugins/kunena/countsimilar/countsimilar.php on line 45

**Comment by androidealp** [comment]
Which version of Kunena? I tested in 4.0.7.
In version 4.0.7, the kunena get object user "$this->me" in event by default in components\com_kunena\views\topic\view.html.php 

``` php
$dispatcher->trigger('onKunenaGetButtons', array('message.action', $this->messageButtons, $this));
```

**Comment by 810** [comment]
This is on the latest version 4.0.9. You need to set error messages to max.

On Tue, Jan 26, 2016 at 7:53 AM -0800, "androidealp" notifications@github.com wrote:

Which version of Kunena? I tested in 4.0.7.
In version 4.0.7, the kunena get object user "$this->me" in event by default in components\com_kunena\views\topic\view.html.php

``` php
$dispatcher->trigger('onKunenaGetButtons', array('message.action', $this->messageButtons, $this));
```

---

**Comment by androidealp** [comment]
ok, i'm download the latest version and correct the error.

**Comment by androidealp** [comment]
I updated the code in the repository, however, carry out tests on the latest version of Kunena, and joomla, and have not found this error. do not know why this happened code. 

The "$this->me" work in kunena 4.0.9. in  components\com_kunena\views\topic\view.html.php line 144.

I went up the images to display the setup process in 4.0.9.

**Comment by 810** [comment]
Ok the code works now, could you also uncount, if they make a mistake

**Comment by androidealp** [comment]
ok, good idea!
I will implement as soon as possible.
